services:
  thingsboard:
    image: thingsboard/tb-postgres:${THINGSBOARD_VERSION:-latest}
    container_name: thingsboard-infra
    restart: unless-stopped
    environment:
      - TB_QUEUE_TYPE=in-memory
    volumes:
      - thingsboard-data:/data
      - thingsboard-logs:/var/log/thingsboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thingsboard.rule=Host(`thingsboard.127.0.0.1.traefik.me`)"
      - "traefik.http.routers.thingsboard.entrypoints=web"
      - "traefik.http.services.thingsboard.loadbalancer.server.port=9090"
    networks:
      - infra-network

volumes:
  thingsboard-data:
  thingsboard-logs:

networks:
  infra-network:
    external: true
